Router.configure({
Router.route('home');
Router.route('about');
Router.route('discover');
Router.route('chat');
Router.route('myprofile');
Router.route('search')
Router.route('sponsors');
Router.route('discover')
)}
